/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tyger;

import com.google.gson.Gson;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

class TxtFilter extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
    }

    @Override
    public String getDescription() {
        return "Arquivos texto (*.txt)";
    }
}

/**
 *
 * @author nfric
 */
public class SabaoGUI extends javax.swing.JFrame {

    private Formula formula;
    private boolean EditMode = false;
    private boolean PendingSave = false;

    /**
     * Creates new form SabaoGUI
     */
    public SabaoGUI() {

        // https://stackoverflow.com/questions/1064977/setting-background-images-in-jframe
        File back = new File("Background.jpg");
        if (back.exists()) {
            try {
                BufferedImage myImage = ImageIO.read(back);
                this.setContentPane(new ImagePanel(myImage));
            } catch (IOException ex) {
                Logger.getLogger(SabaoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        initComponents();

        this.setLocationRelativeTo(null);
        DecimalFormat df = new DecimalFormat("#.#");
        Hashtable labelTable = new Hashtable();
        for (int i = 0; i < 201; i += 10) {
            labelTable.put(i, new JLabel(df.format(i / 10)));
        }
        sldOleo.setLabelTable(labelTable);
        sldAgua.setLabelTable(labelTable);
        sldSoda.setLabelTable(labelTable);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));

        File file = new File("formula padrao.txt");
        if (file.exists() && !file.isDirectory()) {
            ReadFormula(file);
        } else {
            formula = new Formula(5, 2, 1);
            SaveFormula(file);
        }

        sldOleo.setValue((int) (formula.Oleo() * 10.0f));
        sldAgua.setVisible(false);
        sldSoda.setVisible(false);
    }

    private void ReadFormula(File file) {
        String json = null;
        try {
            json = new String(Files.readAllBytes(Paths.get(file.getAbsolutePath())));
            Gson gson = new Gson();
            formula = gson.fromJson(json, Formula.class);
            sldOleo.setValue((int) (formula.Oleo() * 10.0f));
            this.setTitle("Calculadora de Sabão - " + file.getName());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao ler arquivo de fórmula.",
                    "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void SaveFormula(File file) {
        Gson gson = new Gson();
        String json = gson.toJson(formula);
        try (PrintWriter out = new PrintWriter(file)) {
            out.println(json);
            this.setTitle("Calculadora de Sabão - " + file.getName());
            PendingSave = false;
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar arquivo de fórmula.",
                    "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        togOleo = new javax.swing.JToggleButton();
        togAgua = new javax.swing.JToggleButton();
        togSoda = new javax.swing.JToggleButton();
        sldOleo = new javax.swing.JSlider();
        sldAgua = new javax.swing.JSlider();
        lblOleoLitros = new javax.swing.JLabel();
        lblAguaLitros = new javax.swing.JLabel();
        lblSodaKg = new javax.swing.JLabel();
        sldSoda = new javax.swing.JSlider();
        txtOleo = new javax.swing.JFormattedTextField();
        txtAgua = new javax.swing.JFormattedTextField();
        txtSoda = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        fileChooser.setFileFilter(new TxtFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Sabão");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 300));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        togOleo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(togOleo);
        togOleo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        togOleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/oil drop.jpg"))); // NOI18N
        togOleo.setSelected(true);
        togOleo.setText("Óleo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        getContentPane().add(togOleo, gridBagConstraints);

        togAgua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(togAgua);
        togAgua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        togAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/water drop.jpg"))); // NOI18N
        togAgua.setText("Água");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        getContentPane().add(togAgua, gridBagConstraints);

        togSoda.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(togSoda);
        togSoda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        togSoda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/baking soda.jpg"))); // NOI18N
        togSoda.setText("Soda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        getContentPane().add(togSoda, gridBagConstraints);

        sldOleo.setMajorTickSpacing(50);
        sldOleo.setMaximum(200);
        sldOleo.setMinorTickSpacing(10);
        sldOleo.setPaintLabels(true);
        sldOleo.setPaintTicks(true);
        sldOleo.setToolTipText("");
        sldOleo.setValue(0);
        sldOleo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldOleoStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 15);
        getContentPane().add(sldOleo, gridBagConstraints);

        sldAgua.setMaximum(200);
        sldAgua.setPaintLabels(true);
        sldAgua.setPaintTicks(true);
        sldAgua.setValue(0);
        sldAgua.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAguaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 15);
        getContentPane().add(sldAgua, gridBagConstraints);

        lblOleoLitros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblOleoLitros.setText("litros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        getContentPane().add(lblOleoLitros, gridBagConstraints);

        lblAguaLitros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAguaLitros.setText("litros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(lblAguaLitros, gridBagConstraints);

        lblSodaKg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSodaKg.setText("kg");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 5);
        getContentPane().add(lblSodaKg, gridBagConstraints);

        sldSoda.setMaximum(200);
        sldSoda.setPaintLabels(true);
        sldSoda.setPaintTicks(true);
        sldSoda.setValue(0);
        sldSoda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSodaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 15);
        getContentPane().add(sldSoda, gridBagConstraints);

        txtOleo.setEditable(false);
        txtOleo.setBackground(new java.awt.Color(204, 255, 204));
        txtOleo.setColumns(3);
        txtOleo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtOleo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOleo.setFocusable(false);
        txtOleo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtOleo.setMinimumSize(new java.awt.Dimension(66, 44));
        txtOleo.setPreferredSize(new java.awt.Dimension(175, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 0);
        getContentPane().add(txtOleo, gridBagConstraints);

        txtAgua.setEditable(false);
        txtAgua.setBackground(new java.awt.Color(204, 255, 204));
        txtAgua.setColumns(3);
        txtAgua.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtAgua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAgua.setToolTipText("");
        txtAgua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtAgua.setMinimumSize(new java.awt.Dimension(66, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        getContentPane().add(txtAgua, gridBagConstraints);

        txtSoda.setEditable(false);
        txtSoda.setBackground(new java.awt.Color(204, 255, 204));
        txtSoda.setColumns(3);
        txtSoda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtSoda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSoda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSoda.setMinimumSize(new java.awt.Dimension(66, 44));
        txtSoda.setValue(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 0);
        getContentPane().add(txtSoda, gridBagConstraints);

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/save-icon.png"))); // NOI18N
        btnSave.setText("Salvar Fórmula");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(btnSave, gridBagConstraints);

        btnRead.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/open-icon.png"))); // NOI18N
        btnRead.setText("Ler Fórmula");
        btnRead.setName(""); // NOI18N
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(btnRead, gridBagConstraints);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/edit-icon.png"))); // NOI18N
        btnEdit.setText("Editar Fórmula");
        btnEdit.setName(""); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        getContentPane().add(btnEdit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldOleoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldOleoStateChanged
        if (EditMode) {
            txtOleo.setValue((double) sldOleo.getValue() / 10.0f);
            return;
        }
        formula.setRatio((double) sldOleo.getValue() / 10.0f);
        txtOleo.setValue(formula.Oleo());
        txtAgua.setValue(formula.Agua());
        txtSoda.setValue(formula.Soda());
    }//GEN-LAST:event_sldOleoStateChanged

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        if (EditMode) {
            Formula novaFormula = new Formula((double) txtOleo.getValue(), (double) txtAgua.getValue(), (double) txtSoda.getValue());
            if (!formula.equals(novaFormula)) {
                if (JOptionPane.showConfirmDialog(null, "Descartar alterações na fórmula?",
                        "Nova Fórmula", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                    return;
                }
            }
            btnEdit.setText("Editar Fórmula");
            btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/edit-icon.png")));
            btnRead.setText("Ler Fórmula");
            btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/open-icon.png")));
            sldAgua.setVisible(false);
            sldSoda.setVisible(false);
            EditMode = false;
            sldOleo.setValue((int) (formula.Oleo() * 10.0f));
            txtOleo.setValue(formula.Oleo());
            txtAgua.setValue(formula.Agua());
            txtSoda.setValue(formula.Soda());
        } else {
            fileChooser.setDialogTitle("Ler Fórmula");
            if (fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
                return;
            }
            ReadFormula(fileChooser.getSelectedFile());
            txtOleo.setValue(formula.Oleo());
        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        fileChooser.setDialogTitle("Salvar Fórmula");
        if (fileChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        SaveFormula(fileChooser.getSelectedFile());
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditMode = !EditMode;
        if (EditMode) {
            btnEdit.setText("Fórmula OK");
            btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/apply-icon.png")));
            btnRead.setText("Cancelar");
            btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/delete-icon.png")));
            sldAgua.setValue((int) ((double) txtAgua.getValue() * 10.0f));
            sldSoda.setValue((int) ((double) txtSoda.getValue() * 10.0f));
        } else {
            btnEdit.setText("Editar Fórmula");
            btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/edit-icon.png")));
            btnRead.setText("Ler Fórmula");
            btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tyger/open-icon.png")));
            Formula novaFormula = new Formula((double) txtOleo.getValue(), (double) txtAgua.getValue(), (double) txtSoda.getValue());
            if (PendingSave || !formula.equals(novaFormula)) {
                btnSave.setEnabled(true);
                formula = novaFormula;
                this.setTitle("Calculadora de Sabão - nova fórmula*");
                PendingSave = true;
            }
        }
        sldAgua.setVisible(EditMode);
        sldSoda.setVisible(EditMode);
    }//GEN-LAST:event_btnEditActionPerformed

    private void sldAguaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAguaStateChanged
        txtAgua.setValue((double) sldAgua.getValue() / 10.0f);
    }//GEN-LAST:event_sldAguaStateChanged

    private void sldSodaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSodaStateChanged
        txtSoda.setValue((double) sldSoda.getValue() / 10.0f);
    }//GEN-LAST:event_sldSodaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SabaoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SabaoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SabaoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SabaoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SabaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lblAguaLitros;
    private javax.swing.JLabel lblOleoLitros;
    private javax.swing.JLabel lblSodaKg;
    private javax.swing.JSlider sldAgua;
    private javax.swing.JSlider sldOleo;
    private javax.swing.JSlider sldSoda;
    private javax.swing.JToggleButton togAgua;
    private javax.swing.JToggleButton togOleo;
    private javax.swing.JToggleButton togSoda;
    private javax.swing.JFormattedTextField txtAgua;
    private javax.swing.JFormattedTextField txtOleo;
    private javax.swing.JFormattedTextField txtSoda;
    // End of variables declaration//GEN-END:variables
}
